// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExitApp() {
  return window['go']['pkg']['Exit']['ExitApp']();
}

export function SetContext(arg1) {
  return window['go']['pkg']['Exit']['SetContext'](arg1);
}
